require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SeriesController do

  # This should return the minimal set of attributes required to create a valid
  # Serie. As you add validations to Serie, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all series as @series" do
      serie = Serie.create! valid_attributes
      get :index
      assigns(:series).should eq([serie])
    end
  end

  describe "GET show" do
    it "assigns the requested serie as @serie" do
      serie = Serie.create! valid_attributes
      get :show, :id => serie.id.to_s
      assigns(:serie).should eq(serie)
    end
  end

  describe "GET new" do
    it "assigns a new serie as @serie" do
      get :new
      assigns(:serie).should be_a_new(Serie)
    end
  end

  describe "GET edit" do
    it "assigns the requested serie as @serie" do
      serie = Serie.create! valid_attributes
      get :edit, :id => serie.id.to_s
      assigns(:serie).should eq(serie)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Serie" do
        expect {
          post :create, :serie => valid_attributes
        }.to change(Serie, :count).by(1)
      end

      it "assigns a newly created serie as @serie" do
        post :create, :serie => valid_attributes
        assigns(:serie).should be_a(Serie)
        assigns(:serie).should be_persisted
      end

      it "redirects to the created serie" do
        post :create, :serie => valid_attributes
        response.should redirect_to(Serie.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved serie as @serie" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serie.any_instance.stub(:save).and_return(false)
        post :create, :serie => {}
        assigns(:serie).should be_a_new(Serie)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Serie.any_instance.stub(:save).and_return(false)
        post :create, :serie => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested serie" do
        serie = Serie.create! valid_attributes
        # Assuming there are no other series in the database, this
        # specifies that the Serie created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Serie.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => serie.id, :serie => {'these' => 'params'}
      end

      it "assigns the requested serie as @serie" do
        serie = Serie.create! valid_attributes
        put :update, :id => serie.id, :serie => valid_attributes
        assigns(:serie).should eq(serie)
      end

      it "redirects to the serie" do
        serie = Serie.create! valid_attributes
        put :update, :id => serie.id, :serie => valid_attributes
        response.should redirect_to(serie)
      end
    end

    describe "with invalid params" do
      it "assigns the serie as @serie" do
        serie = Serie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serie.any_instance.stub(:save).and_return(false)
        put :update, :id => serie.id.to_s, :serie => {}
        assigns(:serie).should eq(serie)
      end

      it "re-renders the 'edit' template" do
        serie = Serie.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Serie.any_instance.stub(:save).and_return(false)
        put :update, :id => serie.id.to_s, :serie => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested serie" do
      serie = Serie.create! valid_attributes
      expect {
        delete :destroy, :id => serie.id.to_s
      }.to change(Serie, :count).by(-1)
    end

    it "redirects to the series list" do
      serie = Serie.create! valid_attributes
      delete :destroy, :id => serie.id.to_s
      response.should redirect_to(series_url)
    end
  end

end
